server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:

  retry:
    instances:
      dbRetry:
        maxAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true

  circuitbreaker:
    instances:
      dbCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50

